import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';import {fileURLToPath,pathToFileURL} from 'node:url';
const canonical=x=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])])):x;
const raw=x=>Buffer.from(JSON.stringify(canonical(x)));const sha=x=>createHash('sha256').update(x).digest('hex');
async function fixture(){
 const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'office-current-pump-offline-')));await fs.chmod(root,0o700);const evidence=path.join(root,'evidence');await fs.mkdir(evidence,{mode:0o700});const actorRoot=path.join(root,'actor');await fs.mkdir(actorRoot,{mode:0o700});let drivers=0;let clock=1000;
 const item={item_identity_sha256:'f'.repeat(64),file_name:'synthetic.pptx',edit_url:'private-fixture'};
 const lifecycle={createFromBaseline:async()=>({item}),openOwnedDocument:async()=>({id:2})};
 const host={current_native_surface:async()=>({native_metadata:{owned_document_editing:true,window_sha256:'c'.repeat(64)}}),dispatch_native_primitive:async()=>{drivers++;return {status:'applied'};}};
 const context=vm.createContext({Buffer,URL,Date:{now:()=>clock}});const file=new URL('../tools/office_current_cua_pump_v4.mjs',import.meta.url);
 const module=new vm.SourceTextModule(await fs.readFile(file,'utf8'),{context,initializeImportMeta:meta=>{meta.url=file.href;}});
 await module.link(async spec=>{
  const values=spec==='node:fs/promises'?{...fs}:spec==='node:path'?{default:path}:spec==='node:crypto'?{createHash}:spec.includes('ui_lifecycle')?{createOfficeUiLifecycle:async()=>lifecycle}:spec.includes('native_extractor')?{createOfficeNativeExtractor:()=>({})}:{createOfficeOwnedFolderCuaHost:()=>host};
  const m=new vm.SyntheticModule(Object.keys(values),function(){for(const [k,v] of Object.entries(values))this.setExport(k,v);},{context});return m;
 });await module.evaluate();const sources=await module.namespace.officeV4SourceHashes();const binding={supplemental_source_sha256s:sources,account_principal_sha256:'a'.repeat(64),folder_scope_sha256:'b'.repeat(64),browser_id:'synthetic',native_policy_sha256:'d'.repeat(64)};
 const admission={approved:true,...binding,graph_used:false,actual_native_lifecycle_qualified:false};const pump=await module.namespace.createOfficeCuaOperationPump({folderTab:{},browser:{},binding,profile:{signed_in_principal:{editor:{}}},spoolRoot:root,evidenceRoot:evidence,sourceAdmission:admission,listDocumentTabIds:async()=>[]});
 let sequence=0;async function run(operation,payload){const n=sequence++;const dir=path.join(root,'operation-'+String(n).padStart(4,'0'));await fs.mkdir(dir,{mode:0o700});const req={schema:'office-owned-folder-operation-request-v2',operation,sequence:n,payload,account_principal_sha256:binding.account_principal_sha256,folder_scope_sha256:binding.folder_scope_sha256,source_review_sha256:sha(raw(admission)),one_use:true};await fs.writeFile(path.join(dir,'request.private.json'),raw(req),{mode:0o600});await pump.pumpOnce();return JSON.parse(await fs.readFile(path.join(dir,'response.private.json'),'utf8'));}
 await run('create_document',{actor_task:{cell_id:'powerpoint-web'},baseline_path:'private-fixture',purpose:'actor'});await run('actor_open',{item,actor_task:{cell_id:'powerpoint-web'},artifact_root:actorRoot});
 const action={step:0,type:'finish',memory:''};const decision={status:'accepted',policy_sha256:binding.native_policy_sha256};const turn=path.join(actorRoot,'turn-000');await fs.mkdir(turn,{mode:0o700});await fs.writeFile(path.join(turn,'decision.private.json'),raw(decision),{mode:0o600});await fs.writeFile(path.join(turn,'intent.private.json'),raw({action,decision_sha256:sha(raw(decision))}),{mode:0o600});
 return {root,pump,run,item,action,drivers:()=>drivers,setClock:value=>{clock=value;},setClockGetter:value=>{context.Date.now=value;}};
}
test('actual pump consumes expired native dispatch once and refuses before any driver',async()=>{const f=await fixture();try{const r=await f.run('dispatch_native_primitive',{item:f.item,action:f.action,resolved:{},actor_deadline_epoch_ms:999});assert.equal(r.status,'failed');assert.equal(r.result.actor_deadline_rejected,true);assert.equal(r.result.native_driver_attempted,false);assert.equal(r.result.native_operation_may_be_uncertain,false);assert.equal(f.drivers(),0);assert.equal((await f.pump.pumpOnce()).status,'waiting');}finally{await fs.rm(f.root,{recursive:true,force:true});}});
test('actual pump rechecks deadline after asynchronous private guard read and before driver',async()=>{const f=await fixture();try{let calls=0;f.setClockGetter(()=>++calls===1?1000:2000);const r=await f.run('dispatch_native_primitive',{item:f.item,action:f.action,resolved:{},actor_deadline_epoch_ms:1500});assert.equal(r.status,'failed');assert.equal(r.result.native_driver_attempted,false);assert.equal(f.drivers(),0);}finally{await fs.rm(f.root,{recursive:true,force:true});}});
test('actual pump retains native start/end/deadline for one current safe dispatch',async()=>{const f=await fixture();try{const r=await f.run('dispatch_native_primitive',{item:f.item,action:f.action,resolved:{},actor_deadline_epoch_ms:1500});assert.equal(r.status,'completed');assert.equal(r.result.native_driver_started_epoch_ms,1000);assert.equal(r.result.native_driver_completed_epoch_ms,1000);assert.equal(r.result.actor_deadline_epoch_ms,1500);assert.equal(f.drivers(),1);}finally{await fs.rm(f.root,{recursive:true,force:true});}});
