"""Generate a portable interactive evidence explorer, with no remote dependencies."""
import json,shutil
from pathlib import Path
root=Path(__file__).resolve().parents[1];out=root/'outputs';out.mkdir(exist_ok=True)
data=json.loads((out/'evidence.json').read_text());data['issues']=json.loads((root/'datasets/public/kanboard_issues.json').read_text())['records']
img=root/'work/kanboard-public-view.png'
if img.exists():shutil.copyfile(img,out/'kanboard-real-ui.png')
payload=json.dumps(data,ensure_ascii=False).replace('<','\\u003c').replace('>','\\u003e')
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>CUA-RSIBench · Evidence explorer</title>
<style>
:root{--ink:#16343b;--muted:#5d7479;--paper:#f3f1e9;--line:#bfcfc9;--accent:#006b5b;--warning:#a35629}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px 'Avenir Next','PingFang SC','Microsoft Yahei',sans-serif}main{max-width:1240px;margin:auto;padding:40px 42px}header{display:flex;justify-content:space-between;border-bottom:1px solid var(--ink);padding-bottom:20px;font:12px monospace;letter-spacing:1px}a{color:var(--accent)}.hero{padding:62px 0 40px;display:grid;grid-template-columns:2fr 1fr;gap:50px}h1{font:56px Georgia,serif;letter-spacing:-2px;margin:0 0 18px}h2{font-size:28px;font-weight:500;letter-spacing:-.5px}p{line-height:1.8;color:var(--muted)}.tag{font:12px monospace;color:var(--accent);letter-spacing:2px}.note{border-left:3px solid var(--warning);padding:0 18px;align-self:center}.note b{color:var(--warning)}.metrics{display:grid;grid-template-columns:repeat(4,1fr);border-block:1px solid var(--line);margin:20px 0 55px}.metrics div{padding:24px 0}.metrics strong{font:40px Georgia,serif;display:block}.metrics span{font-size:12px;color:var(--muted)}section{margin:50px 0}.flow{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.flow div{border-top:3px solid var(--accent);background:#fff;padding:22px 16px;min-height:150px}.flow b{display:block;margin:14px 0}.flow small{line-height:1.6;color:var(--muted)}button,select,input{font:inherit;padding:10px 14px;border:1px solid var(--line);background:#fff;color:var(--ink);border-radius:0}button{cursor:pointer}button.active{background:var(--ink);color:#fff}.toolbar{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:18px}table{border-collapse:collapse;width:100%;background:#fff;font-size:13px}th,td{padding:15px 14px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:var(--muted)}.scroll{overflow:auto;max-height:650px}.pass{color:var(--accent)}.fail{color:var(--warning)}.muted{color:var(--muted)}.split{display:grid;grid-template-columns:1fr 1fr;gap:36px}.frame{width:100%;border:1px solid var(--line)}details{padding:18px 0;border-bottom:1px solid var(--line)}summary{cursor:pointer;font-weight:500}.legend{font:12px monospace;color:var(--muted)}footer{border-top:1px solid var(--ink);padding:28px 0;margin-top:65px;font-size:12px;color:var(--muted)}@media(max-width:760px){main{padding:24px}.hero,.split{grid-template-columns:1fr}h1{font-size:42px}.flow{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}.hero{padding-top:38px}}
</style>
<main><header><span>CUA-RSIBENCH / EXPERIMENTAL EVIDENCE</span><a href="https://github.com/nanobanana123/cua-rsibench">GitHub ↗</a></header>
<div class="hero"><div><div class="tag">真实软件 · 独立验证</div><h1>From actions<br>to evidence.</h1><p>在真实 Kanboard 中操作真实来源的数据，用独立数据库验收结果。研究、训练和评测的每一层都保留证据。</p><a href="CUA-RSIBench-Technical-Report.pdf">下载技术报告 PDF →</a></div><div class="note"><b>这是试验性证据，不是成熟榜单。</b><p>服务链可用与模型能力提升分别判断。当前不声称持续 RSI 或跨应用泛化。</p></div></div>
<div class="metrics"><div><strong id="issueCount">—</strong><span>真实公开 issue 元数据</span></div><div><strong id="validCount">—</strong><span>完成且有有效验证的原生试验</span></div><div><strong id="infraCount">—</strong><span>单列的基础设施失败</span></div><div><strong id="reward">—</strong><span>合成任务贯通检查的 reward</span></div></div>
<section><span class="tag">01 / FIXED SERVICE CHAIN</span><h2>每一层都有可核验的产物</h2><div class="flow"><div><small>DATA</small><b>训练示范</b><small>训练 split 的 JSONL，包含真实可见观察与动作。</small></div><div><small>TINKER</small><b>LoRA 更新</b><small>真实 optimizer step，保存 sampler checkpoint。</small></div><div><small>E2B</small><b>采样代理</b><small>临时鉴权，独立生命周期，实际 checkpoint sampling。</small></div><div><small>HARBOR</small><b>任务运行</b><small>独立任务沙箱，记录浏览器操作和服务异常。</small></div><div><small>VERIFIER</small><b>独立验收</b><small>读取保存产物，正确性与副作用一起检查。</small></div></div><p>贯通检查使用合成 workbench 任务：当前 reward 为 0，基础设施错误为 0；这不属于原生 Kanboard 能力结果。这是有效负结果，不能称作自我改进。</p></section>
<section><span class="tag">02 / REAL APPLICATION</span><h2>原生界面，真实状态</h2><div class="split"><div><img class="frame" src="kanboard-real-ui.png" alt="实际 E2B 中 Kanboard 原生任务页面"><p class="legend">实际运行截图。应用版本 1.2.54；动作由模型产生。</p></div><div><details open><summary>模型能做什么</summary><p>读取当前可见 DOM 文字和控件，点击、输入、选择、有限按键与返回。模型没有 SQL、文件、shell 或应用 API 工具。</p></details><details><summary>数据哪些是真实的</summary><p>issue 标题、状态、标签、时间戳、评论数和来源 URL 来自公开 GitHub。负责人、工作流政策与排期预算明确标为构造条件。</p></details><details><summary>如何验证</summary><p>主控读取初始和最终 SQLite 状态，检查目标字段及其他任务、描述、评论、项目的完整性。截图和模型自报不是评分依据。</p></details><details><summary>已知限制</summary><p>当前是 DOM 辅助浏览器操作，不是纯像素定位或完整 Windows/macOS 桌面；单次小样本不能推出模型总体排名。</p></details></div></div></section>
<section><span class="tag">03 / RUN EVIDENCE</span><h2>查看每次试验的实际结果</h2><div class="toolbar"><select id="model"><option value="all">全部模型</option><option>gpt-6-astra</option><option>gpt-5.6-sol</option></select><button id="infra">显示基础设施失败</button></div><p id="denominator" class="legend"></p><div class="scroll"><table><thead><tr><th>Run / task</th><th>Model</th><th>Steps</th><th>Result</th><th>Source-state integrity</th></tr></thead><tbody id="trials"></tbody></table></div><p class="legend">重评分仅用于确认原生表单的换行与工时等价归一化；原始结果仍保留。费用 Unknown 不等于 0。</p></section>
<section><span class="tag">04 / SOURCE EXPLORER</span><h2>可追溯的真实数据</h2><div class="toolbar"><input id="search" placeholder="搜索 issue 编号或标题" aria-label="搜索源数据"><select id="state"><option value="all">全部状态</option><option value="open">open</option><option value="closed">closed</option></select></div><div class="scroll"><table><thead><tr><th>Issue</th><th>Title</th><th>State</th><th>Updated at / UTC</th></tr></thead><tbody id="issues"></tbody></table></div></section>
<footer>CUA-RSIBench · 数据和实验状态以 evidence.json 为准。任务仍在校准；正式改进结论需要独立测试与对照。<br><a href="evidence.json">下载结构化证据</a> · <a href="https://github.com/kanboard/kanboard">Kanboard upstream</a> · <a href="https://github.com/evolvent-ai/RSIBench-Data">RSIBench-Data reference</a></footer></main>
<script type="application/json" id="data">PAYLOAD</script><script>
const D=JSON.parse(document.querySelector('#data').textContent);let showInfra=false;
const $=s=>document.querySelector(s);$('#reward').textContent=D.cloud_chain?.reward??'—';$('#issueCount').textContent=D.issues.length;$('#validCount').textContent=D.trials.filter(x=>!x.infrastructure_error&&typeof x.verification.success==='boolean').length;$('#infraCount').textContent=D.trials.filter(x=>x.infrastructure_error).length;
function cell(row,text,cl){let td=document.createElement('td');td.textContent=String(text);if(cl)td.className=cl;row.append(td);return td}
function renderTrials(){let list=D.trials.filter(x=>($('#model').value==='all'||x.model===$('#model').value)&&(showInfra||!x.infrastructure_error));$('#trials').replaceChildren();for(const x of list){let row=document.createElement('tr');cell(row,x.run+' / '+x.case);cell(row,x.model);cell(row,x.steps??'—');cell(row,x.infrastructure_error?'基础设施失败':x.verification.success?'通过':'未通过',x.infrastructure_error?'muted':x.verification.success?'pass':'fail');cell(row,x.infrastructure_error?'未评分':x.verification.wrong_tables?.length?x.verification.wrong_tables.join(', '):'已检查');$('#trials').append(row)}$('#denominator').textContent=`当前展示 ${list.length} 次执行。基础设施失败单列，不混入模型能力成功率。`}
function renderIssues(){let list=D.issues.filter(x=>($('#state').value==='all'||x.state===$('#state').value)&&(''+x.number+' '+x.title).toLowerCase().includes($('#search').value.toLowerCase()));$('#issues').replaceChildren();for(const x of list){let r=document.createElement('tr');let t=cell(r,'');let a=document.createElement('a');a.textContent='#'+x.number;a.href=x.source_url;a.rel='noopener';a.target='_blank';t.append(a);cell(r,x.title);cell(r,x.state);cell(r,x.updated_at);$('#issues').append(r)}}
$('#model').onchange=renderTrials;$('#infra').onclick=()=>{showInfra=!showInfra;$('#infra').classList.toggle('active',showInfra);renderTrials()};$('#search').oninput=renderIssues;$('#state').onchange=renderIssues;renderTrials();renderIssues();
</script></html>'''
(out/'index.html').write_text(html.replace('PAYLOAD',payload))
print('interactive evidence explorer built')
