"""Generate the English portable evidence explorer without remote dependencies."""
import json,re,shutil
from pathlib import Path
from campaign_visualization import SECTION,SCRIPT
ROOT=Path(__file__).resolve().parents[1];out=ROOT/'outputs';out.mkdir(exist_ok=True)
data=json.loads((out/'evidence.json').read_text());data['issues']=json.loads((ROOT/'datasets/public/kanboard_issues.json').read_text())['records']
img=ROOT/'work/kanboard-public-view.png'
if img.exists():shutil.copyfile(img,out/'kanboard-real-ui.png')
payload=json.dumps(data,ensure_ascii=False).replace('<','\\u003c').replace('>','\\u003e')
css=(ROOT/'tools/explorer.css').read_text()
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>EnvLoop | CUA-RSIBench</title><style>STYLE</style>
<main><header><span>ENVLOOP / CUA-RSIBENCH</span><a href="https://github.com/EnvLoop/cua-rsibench">Repository</a></header>
<div class="hero"><div><div class="tag">REAL SOFTWARE / INDEPENDENT VERIFICATION</div><h1>Data research.<br>Verified in real software.</h1><p>Train a fixed student, operate native Kanboard, and check the saved application state. Inspect the data policies, original failures, and resulting evidence.</p><a href="CUA-RSIBench-Technical-Report.pdf">Read the technical report (PDF)</a></div><div class="note"><b>A controlled pilot, with negative results.</b><p>The pipeline executes real training and evaluation. No scored original candidate improves strict task success. This is not a mature leaderboard or evidence of sustained RSI.</p></div></div>
<div class="metrics"><div><strong id="issueCount">-</strong><span>Public issue metadata records</span></div><div><strong id="validCount">-</strong><span>Scored native calibration executions</span></div><div><strong id="infraCount">-</strong><span>Invalid calibration executions</span></div><div><strong>10</strong><span>Actual data-research training attempts</span></div></div>
<section><span class="tag">01 / FIXED SERVICE CHAIN</span><h2>From data recipe to independently checked state</h2><div class="flow"><div><small>DATA</small><b>Verified demonstrations</b><small>Train-only observations and actions, with a recorded selection recipe.</small></div><div><small>TINKER</small><b>Real LoRA updates</b><small>Actual optimizer steps and a persistent sampler checkpoint.</small></div><div><small>E2B</small><b>Sampling proxy</b><small>Temporary authentication and explicit sandbox cleanup.</small></div><div><small>HARBOR</small><b>Native GUI execution</b><small>Separate task environments, action traces and infrastructure diagnostics.</small></div><div><small>VERIFIER</small><b>Saved-state checks</b><small>Correct updates and preservation of unrelated application objects.</small></div></div><p>Integration checks, frontier calibration, original data campaigns and transport-recovery executions are distinct evidence groups.</p></section>
<section><span class="tag">02 / REAL APPLICATION</span><h2>Native interface. Persistent state.</h2><div class="split"><div><img class="frame" src="kanboard-real-ui.png" alt="Recorded native Kanboard task list in E2B"><p class="legend">Kanboard 1.2.54 in an actual E2B execution environment.</p></div><div><details open><summary>What the actor can access</summary><p>Visible DOM text and controls: click, fill, select, limited keypress, back and finish. No shell, SQL, application API, file editing or arbitrary URL tool.</p></details><details><summary>Real data and constructed policies</summary><p>Issue facts and provenance come from public GitHub records. Staff, scheduling rules, planning budgets and archive distractors are explicitly constructed benchmark fields.</p></details><details><summary>Independent verification</summary><p>The evaluator compares initial and final SQLite state, including targets and unrelated objects. Screenshots and model self-reports are not scoring criteria.</p></details><details><summary>Scope</summary><p>DOM-assisted browser use, not pixel-only grounding or a complete Windows/macOS desktop. A small calibration pair does not establish a general model ranking.</p></details></div></div></section>
<section><span class="tag">03 / CALIBRATION</span><h2>Inspect each direct frontier-model execution</h2><div class="toolbar"><select id="model" aria-label="Filter calibration model"><option value="all">All models</option><option>gpt-6-astra</option><option>gpt-5.6-sol</option></select><button id="infra">Show infrastructure-invalid runs</button></div><p id="denominator" class="legend"></p><div class="scroll"><table><thead><tr><th>Run / task</th><th>Model</th><th>Actions</th><th>Outcome</th><th>Saved-state differences</th></tr></thead><tbody id="trials"></tbody></table></div><p class="legend">Regrading normalizes only documented native-form equivalences. Original results remain available. Unknown cost is not zero cost.</p></section>
RESEARCH
<section><span class="tag">05 / SOURCE EXPLORER</span><h2>Traceable public issue metadata</h2><div class="toolbar"><input id="search" placeholder="Search issue number or title" aria-label="Search source records"><select id="state" aria-label="Filter source state"><option value="all">All states</option><option value="open">Open</option><option value="closed">Closed</option></select></div><div class="scroll"><table><thead><tr><th>Issue</th><th>Title</th><th>State</th><th>Updated / UTC</th></tr></thead><tbody id="issues"></tbody></table></div></section>
<footer>EnvLoop - CUA-RSIBench. Results and execution status are recorded in the evidence index.<br><a href="evidence.json">Evidence JSON</a> / <a href="data-campaigns.json">Campaign audit</a> / <a href="https://github.com/kanboard/kanboard">Kanboard</a> / <a href="https://github.com/evolvent-ai/RSIBench-Data">RSIBench-Data reference</a></footer></main>
<script type="application/json" id="data">PAYLOAD</script><script>
const D=JSON.parse(document.querySelector('#data').textContent);let showInfra=false;const $=s=>document.querySelector(s);
$('#issueCount').textContent=D.issues.length;$('#validCount').textContent=D.trials.filter(x=>!x.infrastructure_error&&typeof x.verification.success==='boolean').length;$('#infraCount').textContent=D.trials.filter(x=>x.infrastructure_error).length;
function cell(row,text,cl){let td=document.createElement('td');td.textContent=String(text);if(cl)td.className=cl;row.append(td);return td}
function renderTrials(){let list=D.trials.filter(x=>($('#model').value==='all'||x.model===$('#model').value)&&(showInfra||!x.infrastructure_error));$('#trials').replaceChildren();for(const x of list){let row=document.createElement('tr');cell(row,x.run+' / '+x.case);cell(row,x.model);cell(row,x.steps??'N/A');cell(row,x.infrastructure_error?'Infrastructure error':x.verification.success?'Pass':'Fail',x.infrastructure_error?'muted':x.verification.success?'pass':'fail');cell(row,x.infrastructure_error?'Unscored':x.verification.wrong_tables?.length?x.verification.wrong_tables.join(', '):'No differences');$('#trials').append(row)}$('#denominator').textContent=`Showing ${list.length} executions. Infrastructure-invalid results are excluded from capability scores.`}
function renderIssues(){let list=D.issues.filter(x=>($('#state').value==='all'||x.state===$('#state').value)&&(''+x.number+' '+x.title).toLowerCase().includes($('#search').value.toLowerCase()));$('#issues').replaceChildren();for(const x of list){let r=document.createElement('tr');let t=cell(r,'');let a=document.createElement('a');a.textContent='#'+x.number;a.href=x.source_url;a.rel='noopener';a.target='_blank';t.append(a);cell(r,x.title);cell(r,x.state);cell(r,x.updated_at);$('#issues').append(r)}}
$('#model').onchange=renderTrials;$('#infra').onclick=()=>{showInfra=!showInfra;$('#infra').classList.toggle('active',showInfra);renderTrials()};$('#search').oninput=renderIssues;$('#state').onchange=renderIssues;renderTrials();renderIssues();
SCRIPT
</script></html>'''
html=html.replace('STYLE',css).replace('RESEARCH',SECTION).replace('SCRIPT',SCRIPT).replace('PAYLOAD',payload)
if re.search(r'[\u3400-\u9fff]',html):raise ValueError('non-English CJK content in explorer')
(out/'index.html').write_text(html);print('English evidence explorer built')
