"""Build the English explorer with strict separation of two completed cohorts."""
import argparse
import json
from pathlib import Path
from build_factory_report import ROOT, load_publication, assert_english, write_bundle

EXTRA_CSS = '''
.cohort-panel{border-block:2px solid var(--ink);padding:24px 0;margin:24px 0 0}.cohort-panel label{font-weight:600}.cohort-panel select{max-width:100%;min-width:260px}.cohort-models{font:22px Georgia,serif;color:var(--ink);margin:18px 0 8px}.scope-note{font-size:13px;line-height:1.6;max-width:980px}.rounds{display:flex;gap:9px;flex-wrap:wrap;margin:22px 0}.rounds button{padding:14px 19px}.rounds button.active{background:#173a51;color:#fff}.detail{border-top:2px solid #173a51;padding-top:22px;display:grid;grid-template-columns:1fr 1fr;gap:36px}.score-big{font:64px Georgia,serif;letter-spacing:-3px;line-height:1.2}.budget{height:8px;background:#e5e9ed;margin:14px 0}.budget div{height:100%;background:#087f73}.chart{width:100%;height:auto;margin-top:24px}.method{max-width:820px}.status{font-family:Georgia,serif;font-size:23px}.matrix td.pass{background:#d9efea}.matrix td.fail{background:#edf0f4}.matrix td.unscored{background:#f4e5d6}.hero h1{max-width:800px}.footnote{color:#596271;font-size:13px}.tag{letter-spacing:.14em}.metrics{margin-top:0}.metrics strong{font-variant-numeric:tabular-nums}dl{display:grid;grid-template-columns:1fr 1fr;gap:10px 22px;font-size:14px}dt{color:var(--muted)}dd{margin:0;overflow-wrap:anywhere}.scroll:focus-visible,button:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid #b2632a;outline-offset:4px}.cohort-tag{color:var(--warning);font:12px monospace;text-transform:uppercase}.boundary{border-left:3px solid var(--warning);padding-left:18px}.metrics span{display:block;padding-right:16px}@media(max-width:700px){.detail{grid-template-columns:1fr}.score-big{font-size:52px}.cohort-panel select{width:100%;min-width:0}dl{grid-template-columns:1fr 1fr}}
'''

HTML = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EnvLoop | Two Cohorts of Computer-Use Data Research</title><style>STYLE</style></head><body><main>
<header><span>ENVLOOP / CUA-RSIBENCH</span><a href="https://github.com/EnvLoop/cua-rsibench">Code &amp; releases</a></header>
<div class="hero"><div><div class="tag">EXECUTABLE DATA RESEARCH / TWO SEPARATE COHORTS</div><h1>Data research.<br>Tested in real software.</h1><p>Researcher agents write Python, create native task states, collect verified GUI experience, and train a separate browser student. Every claim follows executed evidence.</p><p id="allModels"></p><a href="CUA-RSIBench-Technical-Report.pdf">Read the English technical report</a></div><div class="note"><b>Two studies. Distinct conditions.</b><p id="comparability"></p><p>Fixed teacher: <strong>gpt-5.6-sol</strong>.<br>Student: <strong>Qwen/Qwen3.5-4B</strong>.</p></div></div>
<div class="cohort-panel"><div class="toolbar"><label for="cohort">Explore a cohort</label><select id="cohort"></select></div><div class="cohort-models" id="cohortModels"></div><p class="scope-note" id="interfaceNote"></p><p class="scope-note" id="baselineNote"></p></div>
<div class="metrics"><div><strong id="roundCount">-</strong><span>Research rounds in this cohort</span></div><div><strong id="trained">-</strong><span>Completed training candidates</span></div><div><strong id="finalCount">-</strong><span>Final task variants in this cohort</span></div><div><strong id="trainingTokens">-</strong><span>Scheduled training tokens in this cohort</span></div></div>
<section><span class="tag">01 / FIXED SERVICES</span><h2>A program, a task state, and a verified outcome</h2><img class="chart" src="figures/factory-pipeline.svg" alt="Researcher code creates training tasks. The fixed gpt-5.6-sol teacher supplies verified GUI experience. Tinker trains Qwen3.5-4B; E2B and Harbor run independent evaluation."><p class="method">The researcher controls generation, filtering, representation, ordering, and mixtures. The controller owns source permissions, budgets, teacher execution, training, evaluation, and checkpoint preservation. Final evidence stays hidden until all searches in its cohort close.</p></section>
<section><span class="tag">02 / EXPERIMENT NOTEBOOK</span><p class="cohort-tag currentCohort"></p><h2>Follow the candidate through each round</h2><p id="headlineOutcome"></p><div class="toolbar"><label for="researcher">Researcher model</label><select id="researcher"></select></div><div class="rounds" id="rounds" aria-label="Choose a research round"></div><div class="detail" aria-live="polite"><div><span class="tag" id="roundLabel"></span><div class="score-big" id="roundScore"></div><p class="status" id="roundStatus"></p><p id="roundExplanation"></p></div><div><dl id="roundFacts"></dl><div class="budget"><div id="budgetFill"></div></div><p class="footnote" id="budgetText"></p></div></div><img class="chart" id="trajectoryChart" alt="Selection trajectories for the selected cohort; unscored rounds are separate from zero outcomes."><p class="footnote">Scores cover three fixed selection instances. Unscored rounds are not zeros. Promotion requires strict mean improvement with no per-task regression. These plots do not compare cohorts under matched conditions.</p><details><summary>Training-resource trajectory</summary><img class="chart" id="budgetChart" alt="Retained selection scores versus scheduled training tokens within the selected cohort."></details></section>
<section><span class="tag">03 / SEALED FINAL TASKS</span><p class="cohort-tag currentCohort"></p><h2>Freeze first. Evaluate afterward.</h2><p class="boundary" id="finalBoundary"></p><div class="toolbar"><label for="role">Comparison role</label><select id="role"></select><label for="outcomeView">Outcome view</label><select id="outcomeView"></select></div><p id="finalSummary" aria-live="polite"></p><div class="scroll" tabindex="0"><table class="matrix"><thead id="finalHead"></thead><tbody id="finalRows"></tbody></table></div><p class="footnote" id="sharedNote"></p><p class="footnote" id="recoveryNote"></p><p class="footnote" id="finalSources"></p><p class="footnote">Repetitions use the same sampling seed in fresh environments. They do not create additional independent task instances. A complete mean remains undefined if any prescribed execution is infrastructure-invalid.</p></section>
<section><span class="tag">04 / ORIGINAL APPLICATION</span><h2>Real interface. Constructed workflows. Saved-state scoring.</h2><div class="split"><div><img class="frame" src="kanboard-real-ui.png" alt="Recorded native Kanboard interface from an E2B run"><p class="legend">Kanboard 1.2.54. Original PHP application and SQLite persistence.</p></div><div><details open><summary>Authentic and synthetic data</summary><p>The snapshot contains 37 public issue metadata records with source URLs and timestamps. Staff, project names, workflow rules, costs, capacities, dependencies, and archive distractors are synthetic. Source pools are separated into training, selection, and final records.</p></details><details><summary>What the browser student can do</summary><p>Read visible DOM text and controls; click, fill, select, use limited keypresses, go back, and finish. No shell, SQL, application API, file editor, or arbitrary URL action is available. Screenshots are audit artifacts.</p></details><details><summary>What earns success</summary><p>A separate verifier compares initial and final application state. Every target update must be correct and unrelated state must remain intact. Declaring completion earns no reward.</p></details><details><summary>What is not measured</summary><p>This is DOM-assisted browser use in one application. It does not measure pixel-only grounding, full Windows/macOS operation, Microsoft Office, broad transfer, or sustained recursive improvement.</p></details></div></div></section>
<section><span class="tag">05 / AUDITABLE RELEASE</span><h2>Separate evidence. Explicit boundaries.</h2><p class="method">The audit reconstructs verified training records, checks dataset and checkpoint bindings, re-reads verifier results, and checks budgets, promotion, and final-test timing. Rejected submissions and infrastructure-invalid outcomes remain visible. Provider dollar costs are unknown.</p><p><a href="factory-study.json">Original cohort evidence</a> / <a href="model6-study.json">Sol 6 / Luna 6 evidence</a> / <a href="combined-study.json">Combined presentation index</a> / <a href="CUA-RSIBench-Technical-Report.md">Manuscript source</a></p><p><a href="https://github.com/EnvLoop/cua-rsibench/releases/tag/v0.4.0-research-pilot">Historical v0.4 selection-only pilot</a></p></section>
<footer>EnvLoop / CUA-RSIBench<br>Inspired by <a href="https://arxiv.org/abs/2607.25886">RSIBench-Data</a>. Results are kept within their experimental cohort.</footer></main>
<script id="publication" type="application/json">PAYLOAD</script><script>JAVASCRIPT</script></body></html>'''

JS = r'''
const P=JSON.parse(document.getElementById('publication').textContent),$=s=>document.querySelector(s),fmt=x=>x===null||x===undefined?'Unscored':(100*x).toFixed(1)+'%';
let active=null,D=null,lookup={},selectedRound=1;
function option(select,value,label){const item=document.createElement('option');item.value=value;item.textContent=label;select.append(item)}
function roleLabel(role){return role==='base'?'Base student':'Student selected by '+D.campaigns.find(c=>c.name===role).researcher}
function addFact(label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;$('#roundFacts').append(dt,dd)}
function renderRound(){const c=D.campaigns.find(c=>c.name===$('#researcher').value),a=c.attempts.find(a=>a.round===selectedRound)||c.attempts[0];selectedRound=a.round;$('#rounds').replaceChildren();for(const r of c.attempts){const b=document.createElement('button');b.textContent='Round '+r.round;b.className=r.round===a.round?'active':'';b.setAttribute('aria-pressed',String(r.round===a.round));b.onclick=()=>{selectedRound=r.round;renderRound()};$('#rounds').append(b)}$('#roundLabel').textContent=c.researcher+' / ROUND '+a.round;$('#roundScore').textContent=fmt(a.evaluation.status==='scored'?a.evaluation.score:null);$('#roundStatus').textContent=a.promoted?'Promoted to incumbent':a.evaluation.status==='scored'?'Incumbent preserved':'No scored checkpoint';$('#roundExplanation').textContent=a.submission_feedback?.reason||(a.evaluation.status==='submission_rejected'?'Submission did not pass the fixed contract. No training score is assigned.':'Task outcomes come from the independent saved-state verifier.');$('#roundFacts').replaceChildren();addFact('Trained browser student',P.student);addFact('Verified training records',a.records??'No accepted training dataset');addFact('Scheduled training tokens',a.training_tokens.toLocaleString());addFact('Incumbent after this round',a.incumbent_after+' / '+fmt(a.best_after));addFact('Accounting',a.accounting);if(a.original_evaluation)addFact('Original selection execution',a.original_evaluation.status+'; current selection score uses its declared recovery');$('#budgetFill').style.width=Math.min(100,100*a.cumulative_training_tokens/c.training_token_budget)+'%';$('#budgetText').textContent=a.cumulative_training_tokens.toLocaleString()+' / '+c.training_token_budget.toLocaleString()+' campaign training tokens used.'}
function renderFinal(){const role=$('#role').value,recovered=$('#outcomeView').value==='recovered',labels=D.final_comparison.bindings[role],runs=labels.map(label=>{const run=lookup[label];return {...run,evaluation:recovered?(run.recovered_evaluation??run.evaluation):run.evaluation}}),tasks=runs[0].evaluation.expected_tasks.slice().sort(),means=runs.map(run=>run.evaluation.status==='scored'?run.evaluation.score:null),mean=means.every(value=>value!==null)?means.reduce((a,b)=>a+b,0)/means.length:null;$('#finalSummary').textContent=(recovered?'Operational recovery / ':'Original executions / ')+roleLabel(role)+': repetition means '+means.map(fmt).join(' / ')+'. Complete mean: '+fmt(mean)+'.';$('#finalHead').replaceChildren();const head=document.createElement('tr'),name=document.createElement('th');name.scope='col';name.textContent='Final task';head.append(name);runs.forEach((run,index)=>{const th=document.createElement('th');th.scope='col';th.textContent='Repetition '+(index+1);head.append(th)});$('#finalHead').append(head);$('#finalRows').replaceChildren();for(const task of tasks){const tr=document.createElement('tr'),th=document.createElement('th');th.scope='row';th.textContent=task;tr.append(th);for(const run of runs){const td=document.createElement('td'),row=run.evaluation.tasks.find(row=>row.task===task),value=row?.error_type?null:row?.score;td.textContent=value===null||value===undefined?'Unscored':value===1?'Pass':'Fail';td.className=value===null||value===undefined?'unscored':value===1?'pass':'fail';tr.append(td)}$('#finalRows').append(tr)}const shared=role!=='base'&&JSON.stringify(labels)===JSON.stringify(D.final_comparison.bindings.base);$('#sharedNote').textContent=shared?'This selection is the base checkpoint. These cells reference the same base executions; they are not additional independent runs.':'Every displayed execution is bound to its frozen checkpoint and sealed task package. No results from the other cohort enter this comparison.';$('#recoveryNote').textContent=recovered?'This view uses audited full-suite replays for infrastructure-invalid slots on a trusted Linux E2B controller. Replayed suites contain six fresh results with unchanged checkpoints, tasks, actor, verifier, and sampling. Valid original slots are preserved. These are the same prescribed repetitions, not new independent samples. Switch to Original executions to inspect unchanged originals.':'This view preserves the original outcomes. Any infrastructure-invalid complete mean stays undefined. Audited operational recoveries, when present, are available as a separate view.'}
function renderCohort(){active=P.cohorts.find(cohort=>cohort.id===$('#cohort').value);D=active.data;lookup=Object.fromEntries(D.final_executions.map(run=>[run.label,run]));selectedRound=1;$('#cohortModels').textContent=active.label+' / '+D.campaigns.map(c=>c.researcher).join(' + ');$('#interfaceNote').textContent=active.interface_note;$('#baselineNote').textContent=active.baseline_note;$('#roundCount').textContent=D.campaigns.reduce((total,c)=>total+c.attempts.length,0);$('#trained').textContent=D.campaigns.flatMap(c=>c.attempts).filter(a=>a.optimizer_steps).length;$('#finalCount').textContent=D.final_tasks;$('#trainingTokens').textContent=D.campaigns.reduce((total,c)=>total+c.used_training_tokens,0).toLocaleString();$('#headlineOutcome').textContent=D.campaigns.map(c=>c.researcher+' retains '+c.selected+' at '+fmt(c.selection_score)+' on selection.').join(' ');document.querySelectorAll('.currentCohort').forEach(node=>{node.textContent=active.label});$('#researcher').replaceChildren();D.campaigns.forEach(c=>option($('#researcher'),c.name,c.researcher));$('#outcomeView').replaceChildren();option($('#outcomeView'),'original','Original executions');if(D.final_executions.some(run=>run.recovered_evaluation))option($('#outcomeView'),'recovered','Operational recovery (same repetitions)');$('#role').replaceChildren();Object.keys(D.final_comparison.bindings).forEach(role=>option($('#role'),role,roleLabel(role)));$('#trajectoryChart').src='figures/factory-'+active.id+'-trajectories.svg';$('#budgetChart').src='figures/factory-'+active.id+'-budget.svg';$('#finalBoundary').textContent='This table uses '+active.label.toLowerCase()+' final instances only. The other cohort has different final source records and instances; cross-cohort ranking is not supported.';$('#finalSources').textContent='This cohort uses '+D.source_records_used.final+' distinct final source records across '+D.final_tasks+' variants. Final IDs are disjoint from train/selection sources, while the application and task templates are shared.';renderRound();renderFinal()}
$('#comparability').textContent=P.comparability;$('#allModels').textContent=P.cohorts.map(cohort=>cohort.label+': '+cohort.data.campaigns.map(c=>c.researcher).join(' and ')+'.').join(' ');P.cohorts.forEach(cohort=>option($('#cohort'),cohort.id,cohort.label));$('#cohort').value=P.cohorts[P.cohorts.length-1].id;$('#cohort').onchange=renderCohort;$('#researcher').onchange=renderRound;$('#role').onchange=renderFinal;$('#outcomeView').onchange=renderFinal;renderCohort();
'''


def build_html(publication):
    payload = json.dumps(publication, ensure_ascii=False).replace('<', '\\u003c').replace('>', '\\u003e').replace('&', '\\u0026')
    css = (ROOT / 'tools/explorer.css').read_text() + EXTRA_CSS
    html = HTML.replace('STYLE', css).replace('JAVASCRIPT', JS).replace('PAYLOAD', payload)
    assert_english(html)
    return html


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-dir', type=Path, default=ROOT / 'outputs')
    parser.add_argument('--out-dir', type=Path, default=ROOT / 'outputs')
    parser.add_argument('--check-only', action='store_true')
    args = parser.parse_args()
    publication = load_publication(args.source_dir)
    html = build_html(publication)
    if args.check_only:
        print('Both cohorts passed explorer gates; no site written.')
        return
    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / 'index.html').write_text(html)
    write_bundle(publication, args.out_dir)
    print('Built the English explorer with two separate completed cohorts.')


if __name__ == '__main__':
    main()
