"""Portable, interactive explorer for the completed executable-factory study."""
import json,re,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];out=ROOT/'outputs';d=json.loads((out/'factory-study.json').read_text())
if not d['search_finished'] or not d['all_final_executions_finished']:raise ValueError('publication requires completed evidence')
payload=json.dumps(d,ensure_ascii=False).replace('<','\\u003c').replace('>','\\u003e')
css=(ROOT/'tools/explorer.css').read_text()+'''
.rounds{display:flex;gap:9px;flex-wrap:wrap;margin:22px 0}.rounds button{border-radius:0;padding:14px 19px}.rounds button.active{background:#173a51;color:#fff}.detail{border-top:2px solid #173a51;padding-top:22px;display:grid;grid-template-columns:1fr 1fr;gap:36px}.score-big{font:64px Georgia,serif;letter-spacing:-3px;line-height:1.2}.budget{height:8px;background:#e5e9ed;margin:14px 0}.budget div{height:100%;background:#087f73}.chart{width:100%;height:auto}.method{max-width:760px}.status{font-family:Georgia,serif;font-size:23px}.matrix td.pass{background:#d9efea}.matrix td.fail{background:#edf0f4}.matrix td.unscored{background:#f4e5d6}.stage{font-variant-numeric:tabular-nums}.hero h1{max-width:800px}.footnote{color:#596271;font-size:13px}.tag{letter-spacing:.14em}.scroll:focus-visible,button:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid #b2632a;outline-offset:4px}@media(max-width:700px){.detail{grid-template-columns:1fr}.score-big{font-size:52px}}
'''
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EnvLoop | Executable Computer-Use Data Research</title><style>STYLE</style></head><body><main>
<header><span>ENVLOOP / CUA-RSIBENCH</span><a href="https://github.com/EnvLoop/cua-rsibench">Code &amp; releases</a></header>
<div class="hero"><div><div class="tag">EXECUTABLE FACTORIES / FIXED EVALUATION</div><h1>Data research.<br>Tested in real software.</h1><p>Two researchers write Python, create native task states, collect verified GUI experience, and train the same student. Inspect what changed and what actually worked.</p><a href="CUA-RSIBench-Technical-Report.pdf">Read the English technical report</a></div><div class="note"><b>A bounded research study.</b><p id="headlineOutcome"></p><p>One application. Three task families. No claim of sustained RSI or a general model ranking.</p></div></div>
<div class="metrics"><div><strong>10</strong><span>Budgeted research rounds</span></div><div><strong id="trained">-</strong><span>Completed training candidates</span></div><div><strong>6</strong><span>Final task variants</span></div><div><strong>37</strong><span>Public issue metadata records</span></div></div>
<section><span class="tag">01 / THE CONTROLLED LOOP</span><h2>A program, a task state, and a verified outcome</h2><img class="chart" src="figures/factory-pipeline.svg" alt="Researcher code generates native training tasks; a fixed teacher and verifier supply traces; Tinker trains the student; Harbor and E2B evaluate it; selection feedback informs the next round."><p class="method">The researcher controls generation, filtering, representation, ordering, and mixtures. The controller owns source permissions, budgets, teacher execution, training, evaluation, and checkpoint preservation. Final evidence is withheld until both searches close.</p></section>
<section><span class="tag">02 / EXPERIMENT NOTEBOOK</span><h2>Follow the candidate, not just the peak</h2><div class="toolbar"><label for="researcher">Researcher</label><select id="researcher"><option value="astra">gpt-6-astra</option><option value="sol">gpt-5.6-sol</option></select></div><div class="rounds" id="rounds" aria-label="Choose a research round"></div><div class="detail" aria-live="polite"><div><span class="tag" id="roundLabel"></span><div class="score-big" id="roundScore"></div><p class="status" id="roundStatus"></p><p id="roundExplanation"></p></div><div><dl id="roundFacts"></dl><div class="budget"><div id="budgetFill"></div></div><p class="footnote" id="budgetText"></p></div></div><img class="chart" src="figures/factory-trajectories.svg" alt="Five-round selection trajectories with unscored submissions shown separately from zero scores."><p class="footnote">Scores cover three fixed selection tasks. Unscored rounds are not zeros. Checkpoint promotion requires strict mean improvement with no per-task regression. Round five explicitly exposed the remaining logical turns after earlier rounds showed submission-deadline ambiguity.</p></section>
<section><span class="tag">03 / SEALED FINAL TASKS</span><h2>Freeze first. Evaluate afterward.</h2><div class="toolbar"><label for="role">Comparison role</label><select id="role"><option value="base">Base student</option><option value="astra">Astra-selected student</option><option value="sol">Sol-selected student</option></select></div><p id="finalSummary" aria-live="polite"></p><div class="scroll" tabindex="0"><table class="matrix"><thead><tr><th>Final task</th><th>Repetition 1</th><th>Repetition 2</th></tr></thead><tbody id="finalRows"></tbody></table></div><p class="footnote" id="sharedNote"></p><p class="footnote">Two fresh-environment repetitions use the same sampling seed. They do not create twelve independent tasks. Final source IDs are disjoint from training and selection. The six variants reuse four final source records, and share task templates and the application.</p></section>
<section><span class="tag">04 / ORIGINAL APPLICATION</span><h2>Real interface. Constructed workflows. Saved-state scoring.</h2><div class="split"><div><img class="frame" src="kanboard-real-ui.png" alt="Recorded Kanboard interface from an E2B run"><p class="legend">Kanboard 1.2.54. The original PHP application and SQLite persistence.</p></div><div><details open><summary>Authentic and synthetic fields</summary><p>Public issue facts retain source URLs and timestamps. Staff, project names, workflow rules, costs, capacity constraints, dependencies, and archive distractors are synthetic benchmark fields.</p></details><details><summary>What the actor can do</summary><p>Visible DOM text and controls; click, fill, select, limited keypress, back, and finish. No shell, SQL, application API, file editor, or arbitrary URL tool. Screenshots are audit artifacts.</p></details><details><summary>What earns success</summary><p>The separate verifier compares initial and final application state. Every target update must be correct and unrelated objects must remain intact. Declaring completion does not earn reward.</p></details><details><summary>Evidence boundaries</summary><p>This is DOM-assisted browser use in one application. It does not measure pixel grounding, full Windows/macOS operation, Microsoft Office, broad transfer, or sustained recursive improvement.</p></details></div></div></section>
<section><span class="tag">05 / AUDITABLE RELEASE</span><h2>The report follows the evidence</h2><p class="method">The audit reconstructs verified training records, checks dataset and checkpoint bindings, re-reads separate-verifier results, verifies budgets and promotion, and checks final-test timing. It retains rejected submissions and infrastructure-invalid executions. Provider dollar totals are unknown, not zero.</p><p><a href="factory-study.json">Download the study evidence</a> / <a href="CUA-RSIBench-Technical-Report.md">Manuscript source</a> / <a href="https://github.com/EnvLoop/cua-rsibench/releases/tag/v0.4.0-research-pilot">Historical v0.4 study</a></p></section>
<footer>EnvLoop / CUA-RSIBench<br>Inspired by <a href="https://arxiv.org/abs/2607.25886">RSIBench-Data</a>. Original failures and protocol repairs remain visible.</footer></main>
<script id="study" type="application/json">PAYLOAD</script><script>
const D=JSON.parse(document.getElementById('study').textContent),$=s=>document.querySelector(s),fmt=x=>x===null?'Unscored':(100*x).toFixed(1)+'%';
const lookup=Object.fromEntries(D.final_executions.map(r=>[r.label,r]));let selectedRound=1;
$('#trained').textContent=D.campaigns.flatMap(c=>c.attempts).filter(a=>a.optimizer_steps).length;
$('#headlineOutcome').textContent=D.campaigns.map(c=>c.researcher+' retains '+c.selected+' at '+fmt(c.selection_score)+' on selection.').join(' ');
function addFact(label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;$('#roundFacts').append(dt,dd)}
function renderRound(){const c=D.campaigns.find(c=>c.name===$('#researcher').value),a=c.attempts.find(a=>a.round===selectedRound)||c.attempts[0];selectedRound=a.round;$('#rounds').replaceChildren();for(const r of c.attempts){const b=document.createElement('button');b.textContent='Round '+r.round;b.className=r.round===a.round?'active':'';b.setAttribute('aria-pressed',String(r.round===a.round));b.onclick=()=>{selectedRound=r.round;renderRound()};$('#rounds').append(b)}$('#roundLabel').textContent=c.researcher+' / ROUND '+a.round;$('#roundScore').textContent=fmt(a.evaluation.score);$('#roundStatus').textContent=a.promoted?'Promoted to incumbent':a.evaluation.status==='scored'?'Incumbent preserved':'No scored checkpoint';$('#roundExplanation').textContent=a.submission_feedback?.reason||(a.evaluation.status==='submission_rejected'?'Submission did not pass the fixed contract. No training score is assigned.':'Task scores come from the independent saved-state verifier.');$('#roundFacts').replaceChildren();addFact('Training records',a.records??'No accepted training dataset');addFact('Scheduled training tokens',a.training_tokens.toLocaleString());addFact('Incumbent after this round',a.incumbent_after+' / '+fmt(a.best_after));addFact('Accounting',a.accounting);$('#budgetFill').style.width=(100*a.cumulative_training_tokens/c.training_token_budget)+'%';$('#budgetText').textContent=a.cumulative_training_tokens.toLocaleString()+' / '+c.training_token_budget.toLocaleString()+' campaign training tokens used.'}
function renderFinal(){const role=$('#role').value,labels=D.final_comparison.bindings[role],runs=labels.map(x=>lookup[x]),tasks=runs[0].evaluation.expected_tasks.slice().sort(),means=runs.map(r=>r.evaluation.score);$('#finalSummary').textContent='Complete means by repetition: '+means.map(fmt).join(' / ')+'.';$('#finalRows').replaceChildren();for(const task of tasks){const tr=document.createElement('tr'),th=document.createElement('th');th.scope='row';th.textContent=task.replace('final-','');tr.append(th);for(const run of runs){const td=document.createElement('td'),v=run.evaluation.tasks.find(t=>t.task===task)?.score;td.textContent=v===null||v===undefined?'Unscored':v===1?'Pass':'Fail';td.className=v===null||v===undefined?'unscored':v===1?'pass':'fail';tr.append(td)}$('#finalRows').append(tr)}const shared=role!=='base'&&JSON.stringify(labels)===JSON.stringify(D.final_comparison.bindings.base);$('#sharedNote').textContent=shared?'This selection is the base checkpoint. These cells reference the same base executions, not additional independent runs.':'Each result is linked to the frozen checkpoint identity and sealed task package.'}
$('#researcher').onchange=renderRound;$('#role').onchange=renderFinal;renderRound();renderFinal();
</script></body></html>'''
html=html.replace('STYLE',css).replace('PAYLOAD',payload)
if re.search(r'[\u3400-\u9fff]',html):raise ValueError('CJK in English site')
(out/'index.html').write_text(html);print('Executable-factory explorer built')
