from pathlib import Path
p=Path('/workspace/factory.py')
s=p.read_text()
s=s.replace("'source-edit-single'", "'source-edit-single-v3'")
s=s.replace("'source-rank-two-triage'", "'source-rank-oldest-pair-v3'")
s=s.replace("[oldest['number'], newest['number'], closed['number'], newer['number']]", "[middle['number'], newer['number'], oldest['number']]")
s=s.replace("'direction': 'desc'", "'direction': 'asc'")
s=s.replace("'owner': 'Rivera', 'priority': 3, 'score': 8", "'owner': 'Chen', 'priority': 2, 'score': 5")
s=s.replace("'source-allocation-dependent-pair'", "'source-allocation-budget-pair-v3'")
s=s.replace("[newer['number'], oldest['number'], middle['number']]", "[newest['number'], middle['number'], newer['number']]")
s=s.replace("'cost_limit': 8, 'hour_limit': 6", "'cost_limit': 9, 'hour_limit': 5")
s=s.replace("{'number': newer['number'], 'cost': 7, 'hours': 5, 'value': 11}", "{'number': newest['number'], 'cost': 9, 'hours': 5, 'value': 14}")
s=s.replace("{'number': oldest['number'], 'cost': 3, 'hours': 2, 'value': 6}", "{'number': middle['number'], 'cost': 4, 'hours': 2, 'value': 8}")
s=s.replace("{'number': middle['number'], 'cost': 5, 'hours': 4, 'value': 10, 'requires': oldest['number']}", "{'number': newer['number'], 'cost': 5, 'hours': 3, 'value': 10, 'requires': middle['number']}")
s=s.replace("'owner': 'Singh', 'priority': 1, 'score': 3", "'owner': 'Rivera', 'priority': 3, 'score': 8")
s=s.replace("Keep a checklist of completed and remaining references.", "Keep a checklist of completed and remaining references. Inspect source metadata in task descriptions; source state is distinct from local task status. Use native task navigation to inspect each candidate. Finish only after all selected references are saved and visibly verified.")
p.write_text(s)
print('Revised inherited factory: three source-derived states; rank oldest two of three; allocation dependency pair beats single expensive alternative.')
